nginx_vhost_files:
  - src: '../shared-files/goshimmer.conf.j2'
  - src: '../shared-files/grafana.conf.j2'
  - src: '../shared-files/prometheus.conf.j2'
  - src: '../shared-files/alertmanager.conf.j2'
